//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ABCSerializer.proto
namespace ABCSerializer
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ABCNode" )]
  public partial class ABCNode : global::ProtoBuf.IExtensible
  {
    public ABCNode() {}

    public int value;
    public int lastCorrectValue;
    public int wildcardIndex;
    public bool wildcard;
    public bool end;
    
    private int _composedValue;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"composedValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public int composedValue
    {
      get { return _composedValue; }
      set {_composedValue = value;}
    }
    private readonly global::System.Collections.Generic.List<ABCNode> _children = new global::System.Collections.Generic.List<ABCNode>();
    [global::ProtoBuf.ProtoMember(2, Name=@"children", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ABCNode> children
    {
      get { return _children; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }

    [global::ProtoBuf.ProtoAfterDeserialization]
    public void InitializeValues() 
    {
        if (System.BitConverter.IsLittleEndian)
        {
            value = (_composedValue & 0x3F);
            wildcardIndex = (_composedValue & (0x3F << 6));
            lastCorrectValue = (_composedValue & (0x3F << 12));
            end = (_composedValue & (0x01 << 18)) == (0x01 << 18);
            wildcard = (_composedValue & (0x01 << 19)) == (0x01 << 19);
        }
        else 
        {
            value = (_composedValue & 0x3F);
            wildcardIndex = (_composedValue & (0x3F >> 6));
            lastCorrectValue = (_composedValue & (0x3F >> 12));
            end = (_composedValue & (0x01 >> 18)) == (0x01 >> 18);
            wildcard = (_composedValue & (0x01 >> 19)) == (0x01 >> 19);
        }
    }

    [global::ProtoBuf.ProtoBeforeSerialization]
    public void setComposedValue()
    {
        if (System.BitConverter.IsLittleEndian)
        {
            _composedValue = (_composedValue & ~0x3F) | (value & 0x3F)
            | (_composedValue & ~(0x3F << 6)) | ((wildcardIndex & 0x3F) << 6)
            | (_composedValue & ~(0x3F << 12)) | ((lastCorrectValue & 0x3F) << 12)
            | (_composedValue & ~(0x01 << 18)) | ((end ? 1 : 0) << 18)
            | (_composedValue & ~(0x01 << 19)) | ((wildcard ? 1 : 0) << 19);
        }
        else 
        {
            _composedValue = (_composedValue & ~0x3F) | (value & 0x3F)
            | (_composedValue & ~(0x3F >> 6)) | ((wildcardIndex & 0x3F) >> 6)
            | (_composedValue & ~(0x3F >> 12)) | ((lastCorrectValue & 0x3F) >> 12)
            | (_composedValue & ~(0x01 >> 18)) | ((end ? 1 : 0) >> 18)
            | (_composedValue & ~(0x01 >> 19)) | ((wildcard ? 1 : 0) >> 19);
        }
        
    }
  }
  
}